# Generated by Django 3.2 on 2021-05-20 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_maincycle_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=10)),
                ('mainCycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.maincycle')),
            ],
        ),
    ]
