# Generated by Django 3.2 on 2021-05-21 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20210521_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boost',
            old_name='mainCycle',
            new_name='main_cycle',
        ),
    ]
