# Generated by Django 3.2 on 2021-06-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0007_auto_20210612_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincycle',
            name='autoClickPower',
            field=models.IntegerField(default=0),
        ),
    ]
